### ISSUE TITLE
Depending on pylint>1.8 breaks Python 2 compatibility

### ISSUE THREAD

**Issue by pquentin** [GoogleCloudPlatform/python-repo-tools#23]
[pylint 2.0+ dropped Python 2 support](https://github.com/PyCQA/pylint/issues/1763), but gcp-devrel-py-tools depends on 'pylint >= 1.8.0'. This is causing the urllib3 CI to fail with Python 2.7.

Is Python 2 intended to be supported? I don't see any PyPI classifiers. I can open a PR to fix the issue by depending on pylint<2.0 for Python 2+.

Thanks!

**Comment by pquentin** [comment]
@theacodes Any thoughts on this issue? Thanks!

**Comment by theacodes** [comment]
> Is Python 2 intended to be supported? I don't see any PyPI classifiers. I can open a PR to fix the issue by depending on pylint<2.0 for Python 2+.

Yeah we have to so that the app engine sdk part will work. To be honest,  I think we can drop pylint/make it an optional dependency. I'm not sure any of our projects are really using pylint any more.

**Comment by pquentin** [comment]
This works now, possibly because we're using pip 9+ in our CI.
